### ISSUE TITLE
Fonctionnalité Map

### ISSUE THREAD

**Issue by njl07** [Sfeir/angular2-200#10]
Le lien pour aller sur la map existe dans le menu `/locator` mais aucune route est associée donc une erreur se produit dans la console.

De même pour le lien sur les cartes des personnes `/locator/:id`

**Comment by njl07** [comment]
Désactivé du menu et de la card à partir de la branche 21

**Comment by cbalit** [comment]
créer une nouvelle step ou tout est branché pour utiliser le webcomponent

**Comment by manekinekko** [comment]
on pourrait introduire les web components dans une SS300
